//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fibertest.StringResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Fibertest.StringResources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0 - Exit.
        /// </summary>
        public static string SID__0___Exit {
            get {
                return ResourceManager.GetString("SID__0___Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 - InitDllsAndConnectOtdr.
        /// </summary>
        public static string SID__1___InitDllsAndConnectOtdr {
            get {
                return ResourceManager.GetString("SID__1___InitDllsAndConnectOtdr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 - DisconnectOtdr.
        /// </summary>
        public static string SID__2___DisconnectOtdr {
            get {
                return ResourceManager.GetString("SID__2___DisconnectOtdr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose action - .
        /// </summary>
        public static string SID_Choose_action___ {
            get {
                return ResourceManager.GetString("SID_Choose_action___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DllInit result is .
        /// </summary>
        public static string SID_DllInit_result_is_ {
            get {
                return ResourceManager.GetString("SID_DllInit_result_is_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Example.
        /// </summary>
        public static string SID_Example {
            get {
                return ResourceManager.GetString("SID_Example", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FreeOtdr result is .
        /// </summary>
        public static string SID_FreeOtdr_result_is_ {
            get {
                return ResourceManager.GetString("SID_FreeOtdr_result_is_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FreeOtdr returned .
        /// </summary>
        public static string SID_FreeOtdr_returned_ {
            get {
                return ResourceManager.GetString("SID_FreeOtdr_returned_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to long operation, please wait....
        /// </summary>
        public static string SID_long_operation_please_wait {
            get {
                return ResourceManager.GetString("SID_long_operation_please_wait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serial is: .
        /// </summary>
        public static string SID_Serial_is__ {
            get {
                return ResourceManager.GetString("SID_Serial_is__", resourceCulture);
            }
        }
    }
}
